services:

  shairport-sync:
    container_name: shairport-sync
    image: ghcr.io/jzucker2/simple-shairport-sync:${SHAIRPORT_SYNC_TAG}
    labels:
      - wud.tag.include=${WUD_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/jzucker2/simple-shairport-sync/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
#    volumes:
#      - /var/run/dbus/:/var/run/dbus/:z
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    cap_add:
      - SYS_NICE # Found in the docs
    environment:
      - AIRPLAY_NAME=${AIRPLAY_NAME}
      - OUTPUT_DEVICE=${AUDIO_OUTPUT_DEVICE}
      - MIXER_CONTROL_NAME=${MIXER_CONTROL_NAME}
      - ENABLE_MQTT=${ENABLE_MQTT}
      - MQTT_HOSTNAME=${MQTT_HOSTNAME}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${MQTT_TOPIC}
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  librespot:
    container_name: librespot
    image: giof71/librespot:${LIBRESPOT_TAG}
    labels:
      - wud.tag.include=${WUD_BOOKWORM_MINOR_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/GioF71/librespot-docker/releases/tag/release%2F$${major}-$${minor}-$${patch}
    restart: unless-stopped
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - librespot-audio-cache:/data/cache
      - librespot-system-cache:/data/system-cache
    environment:
      - DEVICE=${AUDIO_OUTPUT_DEVICE}
      - BACKEND=alsa
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=${SPOTIFY_NAME}
      - ENABLE_CACHE=Y
      - ENABLE_SYSTEM_CACHE=Y
      - CACHE_SIZE_LIMIT=${LIBRESPOT_CACHE_SIZE_LIMIT}

volumes:
  librespot-audio-cache:
    driver: local
  librespot-system-cache:
    driver: local
