services:

  shairport-sync:
    container_name: shairport-sync
    image: mikebrady/shairport-sync:${SHAIRPORT_SYNC_TAG}
    labels:
      - wud.tag.include=${WUD_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/mikebrady/shairport-sync/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    cap_add:
      - SYS_NICE # Found in the docs
    volumes:
      - ./shairport_sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
    logging:
      options:
        max-size: "200k"
        max-file: "10"
