services:

  shairport-sync:
    container_name: shairport-sync
    image: jzucker2/simple-shairport-sync:${SHAIRPORT_SYNC_TAG}
    labels:
      - wud.tag.include=${WUD_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/jzucker2/simple-shairport-sync/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    cap_add:
      - SYS_NICE # Found in the docs
    environment:
      - AIRPLAY_NAME=${AIRPLAY_NAME}
      - OUTPUT_DEVICE=${AUDIO_OUTPUT_DEVICE}
      - HOSTNAME=${MQTT_HOSTNAME}
      - USERNAME=${MQTT_USERNAME}
      - PASSWORD=${MQTT_PASSWORD}
      - TOPIC=${MQTT_TOPIC}
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  librespot:
    container_name: librespot
    image: giof71/librespot:${LIBRESPOT_TAG}
    labels:
      - wud.watch=false
      - wud.tag.include=${WUD_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/GioF71/librespot-docker/releases
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - librespot-audio-cache:/data/cache
      - librespot-system-cache:/data/system-cache
    environment:
      - DEVICE=${AUDIO_OUTPUT_DEVICE}
      - BACKEND=alsa
      - BITRATE=320
      - INITIAL_VOLUME=100
      - DEVICE_NAME=${SPOTIFY_NAME}

volumes:
  librespot-audio-cache:
    driver: local
  librespot-system-cache:
    driver: local
